### ISSUE TITLE
When I use @EventHandler, an error is thrown when the event is triggered

### ISSUE THREAD

**Issue by PengBain** [Nuckerr/paper-kotlin-template#1]
Could not pass event PlayerJoinEvent to xxxxxxx
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

**Comment by PengBain** [comment]
package my.pack

import net.kyori.adventure.text.Component
import org.bukkit.Bukkit
import org.bukkit.event.EventHandler
import org.bukkit.event.Listener
import org.bukkit.event.player.PlayerJoinEvent
import org.bukkit.plugin.java.JavaPlugin

class MyListener: Listener
{
	@EventHandler
	fun onPlayerJoin(event: PlayerJoinEvent)
	{
		event.player.sendMessage( Component.text( "Hello " + event.player.name + " !" ) )
	}

}


class MyPlugin : JavaPlugin() {

	override fun onEnable() {
		logger.info("my plugin loaded")
		Bukkit.getPluginManager().registerEvents( MyListener(), this )
	}

	override fun onDisable() {
		super.onDisable()

	}
}

**Comment by Nuckerr** [comment]
Thanks for bringing this to my attention. Could you send the whole stack trace error please?

**Comment by PengBain** [comment]
> Thanks for bringing this to my attention. Could you send the whole stack trace error please?

I incorrectly executed a run build task resulting in a missing kotlin-std
